version: '3.7'

services:
  django_gunicorn:
    volumes:
    - static:/app/static_files
    build:
      context: .
    ports:
    - "8000:8000"

  nginx:
    build: ./docker_nginx_container
    volumes:
    - static:/app/static_files
    ports:
    - "80:80"
    depends_on:
      - django_gunicorn
volumes:
  static:


