version: '3.7'

services:
  django_gunicorn:
    build:
      context: .
    ports:
    - "8000:8000"
    networks:
      - app-network

  nginx:
    build: ./docker_nginx_container
    ports:
    - "80:80"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - django_gunicorn
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/ --email brightkanyange@outlook.com --agree-tos --no-eff-email --staging -d 2jenge.com  -d www.2jenge.com


volumes:
  certbot-etc:
  certbot-var:


networks:
  app-network:
    driver: bridge

